[workspace]
members = [
  "crates/cli",
  "crates/injector",
  "crates/proxy-mss32",
  "crates/protocol",
  "crates/shim", "crates/pdb-dump", "crates/sdk",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.1"

[profile.release]
lto = true
codegen-units = 1
